const tickerMap = {
  "Apple Inc.": "AAPL",
  "Google LLC": "GOOG",
  "Microsoft Corporation": "MSFT",
  "Tesla, Inc.": "TSLA",
  "Netflix, Inc.": "NFLX",
  "Amazon.com, Inc.": "AMZN",
  "NVIDIA Corporation": "NVDA",
  "Meta Platforms": "META",
  "Intel Corporation": "INTC",
  "Advanced Micro Devices": "AMD",
  "Salesforce Inc.": "CRM",
  "Oracle Corporation": "ORCL",
  "Adobe Inc.": "ADBE",
  "Cisco Systems": "CSCO",
  "International Business Machines": "IBM",
  "Qualcomm": "QCOM",
  "Broadcom Inc.": "AVGO",
  "Texas Instruments": "TXN",
  "Micron Technology": "MU",
  "Shopify Inc.": "SHOP",
  "PayPal Holdings": "PYPL",
  "Uber Technologies": "UBER",
  "Lyft, Inc.": "LYFT",
  "Snowflake Inc.": "SNOW",
  "Palantir Technologies": "PLTR",
  "Walmart Inc.": "WMT",
  "Target Corporation": "TGT",
  "Costco Wholesale": "COST",
  "Coca-Cola Company": "KO",
  "PepsiCo": "PEP",
  "Johnson & Johnson": "JNJ",
  "Pfizer Inc.": "PFE",
  "Moderna Inc.": "MRNA",
  "AbbVie Inc.": "ABBV",
  "Eli Lilly and Company": "LLY",
  "CVS Health": "CVS",
  "UnitedHealth Group": "UNH",
  "Bristol Myers Squibb": "BMY",
  "Gilead Sciences": "GILD",
  "Bank of America": "BAC",
  "JPMorgan Chase": "JPM",
  "Goldman Sachs": "GS",
  "Morgan Stanley": "MS",
  "Citigroup Inc.": "C",
  "Wells Fargo": "WFC",
  "American Express": "AXP",
  "BlackRock": "BLK",
  "Visa Inc.": "V",
  "Mastercard Incorporated": "MA",
  "Discover Financial": "DFS",
  "General Electric": "GE",
  "Honeywell International": "HON",
  "3M Company": "MMM",
  "Caterpillar Inc.": "CAT",
  "Deere & Company": "DE",
  "Boeing Company": "BA",
  "Lockheed Martin": "LMT",
  "Northrop Grumman": "NOC",
  "ExxonMobil": "XOM",
  "Chevron Corporation": "CVX",
  "ConocoPhillips": "COP",
  "Schlumberger": "SLB",
  "Halliburton": "HAL",
  "Walt Disney": "DIS",
  "Starbucks Corporation": "SBUX",
  "Nike, Inc.": "NKE",
  "McDonald's Corporation": "MCD",
  "AT&T Inc.": "T",
  "Verizon Communications": "VZ",
  "FedEx Corporation": "FDX",
  "United Parcel Service": "UPS",
  "Delta Air Lines": "DAL",
  "American Airlines": "AAL",
  "United Airlines": "UAL",
  "Booking Holdings": "BKNG",
  "Royal Caribbean Cruises": "RCL",
  "Carnival Corporation": "CCL",
  "Reliance Industries": "RELIANCE.NS",
  "Tata Consultancy Services": "TCS.NS",
  "Infosys Limited": "INFY.NS",
  "HDFC Bank": "HDFCBANK.NS",
  "ICICI Bank": "ICICIBANK.NS",
  "State Bank of India": "SBIN.NS",
  "Axis Bank": "AXISBANK.NS",
  "Kotak Mahindra Bank": "KOTAKBANK.NS",
  "ITC Limited": "ITC.NS",
  "Larsen & Toubro": "LT.NS",
  "Hindustan Unilever": "HINDUNILVR.NS",
  "Bajaj Finance": "BAJFINANCE.NS",
  "HCL Technologies": "HCLTECH.NS",
  "Wipro Limited": "WIPRO.NS",
  "Tech Mahindra": "TECHM.NS",
  "Oil and Natural Gas Corporation": "ONGC.NS",
  "NTPC Limited": "NTPC.NS",
  "Power Grid Corporation": "POWERGRID.NS",
  "Coal India": "COALINDIA.NS",
  "Bharat Petroleum": "BPCL.NS",
  "Indian Oil Corporation": "IOC.NS",
  "Bharti Airtel": "BHARTIARTL.NS",
  "Sun Pharma": "SUNPHARMA.NS",
  "Tata Motors": "TATAMOTORS.NS",
  "Maruti Suzuki": "MARUTI.NS",
  "Eicher Motors": "EICHERMOT.NS",
  "Hero MotoCorp": "HEROMOTOCO.NS",
  "Bajaj Auto": "BAJAJ-AUTO.NS",
  "Tata Power": "TATAPOWER.NS",
  "Dabur India": "DABUR.NS",
  "Nestle India": "NESTLEIND.NS",
  "Pidilite Industries": "PIDILITIND.NS",
  "Asian Paints": "ASIANPAINT.NS",
  "Britannia Industries": "BRITANNIA.NS",
  "Divi's Laboratories": "DIVISLAB.NS",
  "Adani Enterprises": "ADANIENT.NS",
  "Adani Ports": "ADANIPORTS.NS",
  "UPL Limited": "UPL.NS",
  "UltraTech Cement": "ULTRACEMCO.NS",
  "Shree Cement": "SHREECEM.NS",
  "Grasim Industries": "GRASIM.NS",
  "JSW Steel": "JSWSTEEL.NS",
  "Tata Steel": "TATASTEEL.NS",
  "Hindalco Industries": "HINDALCO.NS",
  "Vedanta Ltd": "VEDL.NS",
  "Zee Entertainment": "ZEEL.NS",
  "GAIL India": "GAIL.NS",
  "Siemens Ltd": "SIEMENS.NS",
  "BHEL": "BHEL.NS",
  "IRCTC": "IRCTC.NS",
  "LIC India": "LICI.NS",
  "Info Edge (Naukri)": "NAUKRI.NS",
  "InterGlobe Aviation (IndiGo)": "INDIGO.NS",
  "Zomato": "ZOMATO.NS",
  "Paytm": "PAYTM.NS",
  "Nykaa": "NYKAA.NS",
  "Polycab": "POLYCAB.NS",
  "Tata Consumer": "TATACONSUM.NS",
  "DMart (Avenue Supermarts)": "DMART.NS",
  "Havells India": "HAVELLS.NS",
  "Ambuja Cements": "AMBUJACEM.NS",
  "ACC Limited": "ACC.NS",
  "Mahindra & Mahindra": "M&M.NS",
  "TVS Motor": "TVSMOTOR.NS",
  "Bharat Electronics": "BEL.NS",
  "Escorts Kubota": "ESCORTS.NS",
  "ABB India": "ABB.NS",
  "Tata Chemicals": "TATACHEM.NS",
  "MRF Tyres": "MRF.NS",
  "Apollo Tyres": "APOLLOTYRE.NS",
  "CEAT Ltd": "CEATLTD.NS",
  "REC Ltd": "RECLTD.NS",
  "Punjab National Bank": "PNB.NS",
  "Canara Bank": "CANBK.NS",
  "Bank of Baroda": "BANKBARODA.NS",
  "IDFC First Bank": "IDFCFIRSTB.NS",
  "IndusInd Bank": "INDUSINDBK.NS",
  "Federal Bank": "FEDERALBNK.NS",
  "Yes Bank": "YESBANK.NS",
  "Bandhan Bank": "BANDHANBNK.NS",
  "AU Small Finance Bank": "AUBANK.NS",
  "Muthoot Finance": "MUTHOOTFIN.NS",
  "Cholamandalam Finance": "CHOLAFIN.NS",
  "LIC Housing Finance": "LICHSGFIN.NS",
  "Shriram Finance": "SHRIRAMFIN.NS",
  "ICICI Prudential Life": "ICICIPRULI.NS",
  "ICICI Lombard": "ICICIGI.NS",
  "HDFC Life": "HDFCLIFE.NS",
  "SBI Life": "SBILIFE.NS",
  "Titan Company": "TITAN.NS",
  "Bosch Ltd": "BOSCHLTD.NS",
  "Cummins India": "CUMMINSIND.NS",
  "Godrej Consumer": "GODREJCP.NS",
  "Colgate Palmolive": "COLPAL.NS",
  "Marico": "MARICO.NS"
};